goal_item/urls.py
from django.conf import settings
from django.urls import include, path
from . import views
from .views import (
    CurrentGoalWeekUpdateView,
    home,
    CurrentGoalWeekDetailView,
    CurrentGoalWeekUpdateView,
)


app_name = "weeks"

urlpatterns = [
    path('', home, name='home'),
    path('weeks/<int:pk>/', CurrentGoalWeekDetailView.as_view(), name='week-detail'),
    path('weeks/<int:pk>/update/', CurrentGoalWeekUpdateView.as_view(), name='week-update'),
]

goalsapp/urls.py
from django.contrib import admin
from django.urls import include, path
from goal_item.views import CurrentGoalWeekCreateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('weeks/create/', CurrentGoalWeekCreateView.as_view(), name='week-create'),
    path('', include('goal_item.urls', namespace='items')),
]

goal_item/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, m2m_changed
from django.dispatch import receiver


class User(AbstractUser):
    pass


class GoalItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    value = models.PositiveSmallIntegerField(default=1)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)
    date_of_goal = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email


class CurrentGoalWeek(models.Model):
    week_start_date = models.DateField(auto_now_add=False)
    week_end_date = models.DateField(null=True, blank=True, auto_now_add=False)
    gd1_run = models.BooleanField(default=False)
    gd1_water = models.BooleanField(default=False)
    gd1_smoothie = models.BooleanField(default=False)
    gd1_read = models.BooleanField(default=False)
    day1_is_complete = models.BooleanField(default=False)
    gd1_extra_point = models.BooleanField(default=False)
    gd2_run = models.BooleanField(default=False)
    gd2_water = models.BooleanField(default=False)
    gd2_smoothie = models.BooleanField(default=False)
    gd2_read = models.BooleanField(default=False)
    day2_is_complete = models.BooleanField(default=False)
    gd2_extra_point = models.BooleanField(default=False)
    gd3_run = models.BooleanField(default=False)
    gd3_water = models.BooleanField(default=False)
    gd3_smoothie = models.BooleanField(default=False)
    gd3_read = models.BooleanField(default=False)
    day3_is_complete = models.BooleanField(default=False)
    gd3_extra_point = models.BooleanField(default=False)
    gd4_run = models.BooleanField(default=False)
    gd4_water = models.BooleanField(default=False)
    gd4_smoothie = models.BooleanField(default=False)
    gd4_read = models.BooleanField(default=False)
    day4_is_complete = models.BooleanField(default=False)
    gd4_extra_point = models.BooleanField(default=False)
    gd5_run = models.BooleanField(default=False)
    gd5_water = models.BooleanField(default=False)
    gd5_smoothie = models.BooleanField(default=False)
    gd5_read = models.BooleanField(default=False)
    day5_is_complete = models.BooleanField(default=False)
    gd5_extra_point = models.BooleanField(default=False)
    week_extra_2points = models.BooleanField(default=False)
    choose_goals = models.ManyToManyField(GoalItem, blank=True, related_name=('choose_goals'))
    is_active_week = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.week_start_date}'

    
class CurrentGoalDay(models.Model):
    week_day = models.PositiveSmallIntegerField()
    goal_week = models.ForeignKey(CurrentGoalWeek, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.goal_week} (day {self.week_day})'


class DayOne(models.Model):
    goal_week = models.OneToOneField(CurrentGoalWeek, on_delete=models.CASCADE, related_name="goal_week")
    day_is_complete = models.BooleanField(default=False)
    day_one_goals = models.ManyToManyField(GoalItem, blank=True)

    def __str__(self):
        return f'{self.goal_week} (Day #1)'


# @receiver(post_save, sender=CurrentGoalWeek)
# def create_days(sender, instance, created, **kwargs):
#     if created:
#         DayOne.objects.create(
#             goal_week = instance,
#         )
#         print(instance)
#         print('?&?&?&?&?&   created new DayOne  ?&?&?&?&?&?&?&&?')


# @receiver(m2m_changed, sender=CurrentGoalWeek.choose_goals.through)
# def add_the_goals(sender, instance, action, **kwargs):
#     if action:
#         # goal_list = instance.objects.get()
#         # DayOne.objects.update(instance)
#         print('<<<<<<<<<<<<<<<   m2m_changed reciever went through >>>>>>>>>>>>>>>>>>')
#         print(instance)



# class DayTwo(models.Model):
#     goal_week = models.OneToOneField(CurrentGoalWeek, on_delete=models.CASCADE)
#     day_is_complete = models.BooleanField(default=False)

#     def __str__(self):
#         return f'{self.goal_week} (Day #2)'


# class DayThree(models.Model):
#     goal_week = models.OneToOneField(CurrentGoalWeek, on_delete=models.CASCADE)
#     day_is_complete = models.BooleanField(default=False)

#     def __str__(self):
#         return f'{self.goal_week} (Day #3)'


# class DayFour(models.Model):
#     goal_week = models.OneToOneField(CurrentGoalWeek, on_delete=models.CASCADE)
#     day_is_complete = models.BooleanField(default=False)

#     def __str__(self):
#         return f'{self.goal_week} (Day #4)'


# class DayFive(models.Model):
#     goal_week = models.OneToOneField(CurrentGoalWeek, on_delete=models.CASCADE)
#     day_is_complete = models.BooleanField(default=False)

#     def __str__(self):
#         return f'{self.goal_week} (Day #5)'

goal_item/forms.py
from django import forms
from .models import CurrentGoalWeek, GoalItem


class GoalItemModelForm(forms.ModelForm):
    class Meta:
        model = GoalItem
        fields = (
            'name',
            'description',
            'value',
            'agent',
            'is_complete'
        )

class DateInput(forms.DateInput):
    input_type = 'date'


class CurrentGoalWeekModelForm(forms.ModelForm):
    class Meta:
        model = CurrentGoalWeek
        widgets = {'week_start_date': DateInput()}
        fields = (
            'week_start_date',
        )





class CurrentGoalWeekUpdateForm(forms.ModelForm):

    class Meta:
        model = CurrentGoalWeek
        fields = [
            'gd1_run',
            'gd1_water',
            'gd1_smoothie',
            'gd1_read',
            'gd2_run',
            'gd2_water',
            'gd2_smoothie',
            'gd2_read',
            'gd3_run',
            'gd3_water',
            'gd3_smoothie',
            'gd3_read',
            'gd4_run',
            'gd4_water',
            'gd4_smoothie',
            'gd4_read',
            'gd5_run',
            'gd5_water',
            'gd5_smoothie',
            'gd5_read'
        ]

goal_item/views.py
from django.db.models import query
from goaldays.models import GoalDayOne
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import GoalItem, Agent, CurrentGoalDay, CurrentGoalWeek
from django.views import generic
from django.views.generic import (
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.urls import reverse
from .forms import (
    GoalItemModelForm,
    CurrentGoalWeekModelForm,
    CurrentGoalWeekUpdateForm,
)


def home(request):
    context = {
        'weeks': CurrentGoalWeek.objects.filter(is_active_week=False),
        'd1_bool_yes': CurrentGoalWeek.objects.filter(day1_is_complete=True).count(),
        'd2_bool_yes': CurrentGoalWeek.objects.filter(day2_is_complete=True).count(),
        'active_week': CurrentGoalWeek.objects.filter(is_active_week=True)
    }
    return render(request, 'goal_item/home.html', context)


class CurrentGoalWeekDetailView(DetailView):
    model = CurrentGoalWeek
    # Dont think context_ob_name is needed anymore
    context_object_name = "week"

    def get_context_data(self, **kwargs):
        context = super(CurrentGoalWeekDetailView, self).get_context_data(**kwargs)
        week = self.get_object()
    # day 1
        if week.gd1_run:
            gd1_run_value = str("x")
        else:
            gd1_run_value = str("")
        if week.gd1_water:
            gd1_water_value = str("x")
        else:
            gd1_water_value = str("")
        if week.gd1_smoothie:
            gd1_smoothie_value = str("x")
        else:
            gd1_smoothie_value = str("")
        if week.gd1_read:
            gd1_read_value = str("x")
        else:
            gd1_read_value = str("")
        day_1_list = [week.gd1_run, week.gd1_water, week.gd1_smoothie, week.gd1_read]
        day_1_list_total = 0
        for x in day_1_list:
            if x == True:
                day_1_list_total += 1
        if day_1_list_total == 4:
            gd1_extra_point_value = str(":-)")
        else:
            gd1_extra_point_value = str(":-(")
    
    # day 2
        if week.gd2_run:
            gd2_run_value = str("x")
        else:
            gd2_run_value = str("")
        if week.gd2_water:
            gd2_water_value = str("x")
        else:
            gd2_water_value = str("")
        if week.gd2_smoothie:
            gd2_smoothie_value = str("x")
        else:
            gd2_smoothie_value = str("")
        if week.gd2_read:
            gd2_read_value = str("x")
        else:
            gd2_read_value = str("")
        day_2_list = [week.gd2_run, week.gd2_water, week.gd2_smoothie, week.gd2_read]
        day_2_list_total = 0
        for x in day_2_list:
            if x == True:
                day_2_list_total += 1
        if day_2_list_total == 4:
            gd2_extra_point_value = str(":-)")
        else:
            gd2_extra_point_value = str(":-(")
    
    # day 3
        if week.gd3_run:
            gd3_run_value = str("x")
        else:
            gd3_run_value = str("")
        if week.gd3_water:
            gd3_water_value = str("x")
        else:
            gd3_water_value = str("")
        if week.gd3_smoothie:
            gd3_smoothie_value = str("x")
        else:
            gd3_smoothie_value = str("")
        if week.gd3_read:
            gd3_read_value = str("x")
        else:
            gd3_read_value = str("")
        day_3_list = [week.gd3_run, week.gd3_water, week.gd3_smoothie, week.gd3_read]
        day_3_list_total = 0
        for x in day_3_list:
            if x == True:
                day_3_list_total += 1
        if day_3_list_total == 4:
            gd3_extra_point_value = str(":-)")
        else:
            gd3_extra_point_value = str(":-(")
    
    # day 4
        if week.gd4_run:
            gd4_run_value = str("x")
        else:
            gd4_run_value = str("")
        if week.gd4_water:
            gd4_water_value = str("x")
        else:
            gd4_water_value = str("")
        if week.gd4_smoothie:
            gd4_smoothie_value = str("x")
        else:
            gd4_smoothie_value = str("")
        if week.gd4_read:
            gd4_read_value = str("x")
        else:
            gd4_read_value = str("")
        day_4_list = [week.gd4_run, week.gd4_water, week.gd4_smoothie, week.gd4_read]
        day_4_list_total = 0
        for x in day_4_list:
            if x == True:
                day_4_list_total += 1
        if day_4_list_total == 4:
            gd4_extra_point_value = str(":-)")
        else:
            gd4_extra_point_value = str(":-(")
    
    # day 5
        if week.gd5_run:
            gd5_run_value = str("x")
        else:
            gd5_run_value = str("")
        if week.gd5_water:
            gd5_water_value = str("x")
        else:
            gd5_water_value = str("")
        if week.gd5_smoothie:
            gd5_smoothie_value = str("x")
        else:
            gd5_smoothie_value = str("")
        if week.gd5_read:
            gd5_read_value = str("x")
        else:
            gd5_read_value = str("")
        day_5_list = [week.gd5_run, week.gd5_water, week.gd5_smoothie, week.gd5_read]
        day_5_list_total = 0
        for x in day_5_list:
            if x == True:
                day_5_list_total += 1
        if day_5_list_total == 4:
            gd5_extra_point_value = str(":-)")
        else:
            gd5_extra_point_value = str(":-(")

    # context
        context = {
            'week': week,
            # day 1
            'gd1_run_value': gd1_run_value,
            'gd1_water_value': gd1_water_value,
            'gd1_smoothie_value': gd1_smoothie_value,
            'gd1_read_value': gd1_read_value,
            'gd1_extra_point_value': gd1_extra_point_value,
            'day_1_list_total': day_1_list_total,
            # day 2
            'gd2_run_value': gd2_run_value,
            'gd2_water_value': gd2_water_value,
            'gd2_smoothie_value': gd2_smoothie_value,
            'gd2_read_value': gd2_read_value,
            'gd2_extra_point_value': gd2_extra_point_value,
            'day_2_list_total': day_2_list_total,
            # day 3
            'gd3_run_value': gd3_run_value,
            'gd3_water_value': gd3_water_value,
            'gd3_smoothie_value': gd3_smoothie_value,
            'gd3_read_value': gd3_read_value,
            'gd3_extra_point_value': gd3_extra_point_value,
            'day_3_list_total': day_3_list_total,
            # day 4
            'gd4_run_value': gd4_run_value,
            'gd4_water_value': gd4_water_value,
            'gd4_smoothie_value': gd4_smoothie_value,
            'gd4_read_value': gd4_read_value,
            'gd4_extra_point_value': gd4_extra_point_value,
            'day_4_list_total': day_4_list_total,
            # day 5
            'gd5_run_value': gd5_run_value,
            'gd5_water_value': gd5_water_value,
            'gd5_smoothie_value': gd5_smoothie_value,
            'gd5_read_value': gd5_read_value,
            'gd5_extra_point_value': gd5_extra_point_value,
            'day_5_list_total': day_5_list_total,
        }
        return context


class CurrentGoalWeekCreateView(generic.CreateView):
    template_name = "goal_item/currentgoalweek_create.html"
    form_class = CurrentGoalWeekModelForm

    def get_success_url(self):
        print('!!VIEWS!!: week created')
        print(self.currentgoalweek)
        return reverse("weeks:week-detail", kwargs={
            "pk": self.currentgoalweek.id
        })

    def form_valid(self, form):
        instance = form.save(commit=False)
        # instance.user = self.request.user
        instance.save()
        self.currentgoalweek = instance
        return super(CurrentGoalWeekCreateView, self).form_valid(form)


class CurrentGoalWeekUpdateView(generic.UpdateView):
    template_name = "goal_item/currentgoalweek_update.html"
    model = CurrentGoalWeek
    form_class = CurrentGoalWeekUpdateForm

    def get_success_url(self):
        print('!!VIEWS!!: week updated')
        return reverse("weeks:home")

goal_item/templates/goal_item/currentgoalweek_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<h2>create goal week</h2>

<div class="mt-4">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="mt-6">
            <span class="block w-full rounded-md shadow-sm">
                <button type="submit"
                        class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:border-blue-700 focus:shadow-outline-blue active:bg-blue-700 transition duration-150 ease-in-out">
                        Submit
                </button>
            </span>
        </div>
    </form>
</div>

{% endblock content %}s

goal_item/templates/goal_item/currentgoalweek_detail.html
{% extends 'base.html' %}
{% block content %}

<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
</style>

<a href="{% url 'weeks:home' %}">Back to home</a>
<hr />

    <h1>Week: {{ week.week_start_date|date:"M d" }}</h1><small><a href="{% url 'weeks:week-update' week.id %}">(Update)</a></small>
    <h3>possible points: </h3>

<table>
    <!-- headers -->
    <tr>
      <th>Goal</th>
      <th>Day #1</th>
      <th>Day #2</th>
      <th>Day #3</th>
      <th>Day #4</th>
      <th>Day #5</th>
    </tr>
    <tr>
        <td>Run</td>
        <td>{{ gd1_run_value }}</td>
        <td>{{ gd2_run_value }}</td>
        <td>{{ gd3_run_value }}</td>
        <td>{{ gd4_run_value }}</td>
        <td>{{ gd5_run_value }}</td>
    </tr>
    <tr>
        <td>Water</td>
        <td>{{ gd1_water_value }}</td>
        <td>{{ gd2_water_value }}</td>
        <td>{{ gd3_water_value }}</td>
        <td>{{ gd4_water_value }}</td>
        <td>{{ gd5_water_value }}</td>
    </tr>
    <tr>
        <td>Smoothie</td>
        <td>{{ gd1_smoothie_value }}</td>
        <td>{{ gd2_smoothie_value }}</td>
        <td>{{ gd3_smoothie_value }}</td>
        <td>{{ gd4_smoothie_value }}</td>
        <td>{{ gd5_smoothie_value }}</td>
    </tr>
    <tr>
        <td>Read</td>
        <td>{{ gd1_read_value }}</td>
        <td>{{ gd2_read_value }}</td>
        <td>{{ gd3_read_value }}</td>
        <td>{{ gd4_read_value }}</td>
        <td>{{ gd5_read_value }}</td>
    </tr>
    <tr>
        <td>Extra Point Achieved?</td>
        <td>{{ gd1_extra_point_value }}</td>
        <td>{{ gd2_extra_point_value }}</td>
        <td>{{ gd3_extra_point_value }}</td>
        <td>{{ gd4_extra_point_value }}</td>
        <td>{{ gd5_extra_point_value }}</td>
    </tr>
  </table>


  <h2>Day 1 list total: {{ day_1_list_total }}</h2>
  <h2>Day 2 list total: {{ day_2_list_total }}</h2>
  <h2>Day 3 list total: {{ day_3_list_total }}</h2>
  <h2>Day 4 list total: {{ day_4_list_total }}</h2>

{% endblock content %}

goal_item/templates/goal_item/currentgoalweek_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h2>Update Gaol Week: {{ object.week_start_date }}</h2>

    <div class="mt-4">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="mt-6">
                <span class="block w-full rounded-md shadow-sm">
                    <button type="submit"
                            class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:border-blue-700 focus:shadow-outline-blue active:bg-blue-700 transition duration-150 ease-in-out">
                            Submit
                    </button>
                </span>
            </div>
        </form>
    </div>

    <hr />

    <a href="{% url 'weeks:week-detail' object.id %}">Back to week</a>


{% endblock content %}s

goal_item/templates/goal_item/goalitem_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h2>create goal</h2>

<div class="mt-4">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="mt-6">
            <span class="block w-full rounded-md shadow-sm">
                <button type="submit"
                        class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:border-blue-700 focus:shadow-outline-blue active:bg-blue-700 transition duration-150 ease-in-out">
                        Submit
                </button>
            </span>
        </div>
    </form>
</div>



<div>
    <hr />
    <a href="{% url 'items:item-list' %}">Back to goals</a>
</div>

{% endblock content %}

goal_item/templates/goal_item/goals.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>goals.html test</h1>
</body>
</html>

goal_item/templates/goal_item/home.html
{% extends 'base.html' %}

{% block content %}

<!-- test for git -->

    <div class="btn">
        <a class="btn btn-primary" href="{% url 'week-create' %}">Create a new week</a>
    </div>
    <hr />
    {% for x in active_week %}
    <h4>Active Week: <a href="{% url 'weeks:week-detail' x.id %}">{{ x.week_start_date|date:"M d" }}</a></h4>

<table class="table mb-4">
    <tbody>
      <tr>
        <th>Goal</td>
        <th>Day #1</td>
        <th>Day #2</td>
        <th>Day #3</td>
        <th>Day #4</td>
        <th>Day #5</td>
      </tr>
      <tr>
        <td>Run</td>
        <td>{{ x.gd1_run }}</td>
        <td>{{ x.gd2_run }}</td>
        <td>{{ x.gd3_run }}</td>
        <td>{{ x.gd4_run }}</td>
        <td>{{ x.gd5_run }}</td>
      </tr>
      <tr>
        <td>Water</td>
        <td>{{ x.gd1_water }}</td>
        <td>{{ x.gd2_water }}</td>
        <td>{{ x.gd3_water }}</td>
        <td>{{ x.gd4_water }}</td>
        <td>{{ x.gd5_water }}</td>
    </tr>
    <tr>
        <td>Smoothie</td>
        <td>{{ x.gd1_smoothie }}</td>
        <td>{{ x.gd2_smoothie }}</td>
        <td>{{ x.gd3_smoothie }}</td>
        <td>{{ x.gd4_smoothie }}</td>
        <td>{{ x.gd5_smoothie }}</td>
    </tr>
    <tr>
        <td>Read</td>
        <td>{{ x.gd1_read }}</td>
        <td>{{ x.gd2_read }}</td>
        <td>{{ x.gd3_read }}</td>
        <td>{{ x.gd4_read }}</td>
        <td>{{ x.gd5_read }}</td>
    </tr>
    <tr>
        <td>Extra Point Achieved?</td>
        <td>{{ x.gd1_extra_point }}</td>
        <td>{{ x.gd2_extra_point }}</td>
        <td>{{ x.gd3_extra_point }}</td>
        <td>{{ x.gd4_extra_point }}</td>
        <td>{{ x.gd5_extra_point }}</td>
    </tr>
    </tbody>
 </table>
{% endfor %}

    <h2>Overall Daily Success Percentage: {{ d1_bool_yes|add:d2_bool_yes|add:25 }}%</h2>
    <p>AKA: days with is_complete=True vs days with False</p>
    <h2>Overall Weekly Success Percentage: __%</h2>
    <p>AKA: weeks with is_complete=True vs days with False</p>

{% for week in weeks %}
    Past Weeks Dropdown:
    <h4>Week: <a href="{% url 'weeks:week-detail' week.id %}">{{ week }}</a></h4>
{% endfor %}



{% endblock content %}

goal_item/templates/goal_item/item_detail.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'items:item-list' %}">Go back to Items</a>
    <hr />
    <h1>This is the details of {{ item.name }}</h1>
    <p>description: {{ item.description }}</p>
    <p>value: {{ item.value }}</p>
    <p>agent: {{ item.agent }}</p>
    <p>is_complete: {{ item.is_complete }}</p>
    <p>item id: {{ item.id }}</p>

{% endblock content %}

goal_item/templates/goal_item/item_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'goal-create' %}">Create a new goal</a>
    <hr />
    <h1>This is all of our goals</h1>
    {% for item in items %}
        <div class="item">
            <a href="{% url 'items:item-detail' item.pk %}">{{ item.name }}</a>
        </div>
    {% endfor %}
    <h1>This is toms goals</h1>
    {% for item in toms_items %}
        <div class="item">
            <a href="{% url 'items:item-detail' item.pk %}">{{ item.name }}</a>
        </div>
    {% endfor %}
    <h1>These are all the agents</h1>
    {% for agent in agents %}
        <div class="item">
            <a href="#">{{ agent.user }}</a>
            {% for x in agent.user.name %}
                <p>Goal: {{ x.name }}</p>
            {% endfor %}
        </div>
    {% endfor %}

{% endblock content %}

goal_item/templates/goal_item/this_week.html
{% extends 'base.html' %}
{% block content %}

<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
</style>



    <h1>Week: {{ this_week }}</h1>
    <h3>possible points: {{ weeks_possible_points }}</h3>
    <h1>This weeks Goals</h1>

{% for goal in weeks_goals %}
    <h3>Goal: {{ goal }}</h3>
{% endfor %}

<table>
    <tr>
      <th>Goal</th>
      <th>Day #1</th>
      <th>Day #2</th>
      <th>Day #3</th>
      <th>Day #4</th>
      <th>Day #5</th>
    </tr>
    
    {% for goal in weeks_goals %}
        <tr>
            <td>{{ goal }}</td>
            <td>X</td>
            <td>X</td>
            <td>X</td>
            <td>X</td>
            <td>X</td>
        </tr>
    {% endfor %}
  </table>


  <h3>Day 1</h3>
  <p>day 1: {{ this_week_d1 }}</p>

{% endblock content %}